refactor(prometheus): modularize scrape configs from prom-ksonnet
grafana/jsonnet-libs pull request #494
Opened 2021-03-12 12:31 UTC by Duologic

prometheus-ksonnet contains a number of very useful scrape configs, this PR aims to modularize them so they can easily
be included in other implementations.

I've taken the opportunity to order the relabel configs in the `kubernetes-pods` scrape config a bit more logically,
they don't seem to depend on each other so the order should not change the end result. I've sorted them following this
pattern:

- keep/drop pods
- handle prometheus annotations
- namespace and pod name labels

2021-03-12 13:36 UTC, malcolmholmes approved these changes
YAY! Much cleaner

2021-03-17 19:55 UTC, beorn7 requested changes
Just nits. I think the sorting of the relabeling config is fine.

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/kube-state-metrics.libsonnet
> +          // Drop anything who's service is not kube-state-metrics
I know it's just copied, but perhaps fix spelling, now that we are on it: who's → whose, and I find sentences easier to read if they end with a period.

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/kube-state-metrics.libsonnet
> +          // Rename jobs to be <namespace>/<name, from pod name label>
This line is a leftover and needs to go. (Again, was the case previously, but let's fix.)

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/node-exporter.libsonnet
> +          // Drop anything who's name is not node-exporter.
who's → whose

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/node-exporter.libsonnet
> +          // But also include the namespace as a separate label, for routing alerts
End with period.

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/prometheus-config.libsonnet
> +      // Grafana Labs' battle tested scrape config for scraping kubernetes pods
End with period.

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/prometheus-config.libsonnet
> +      // `scrape_configs.kubernetes_pods`
End with period.

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/prometheus-config.libsonnet
>        // This scrape config gather all kubelet metrics.
gather → gathers

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/prometheus-config.libsonnet
> +        // Couldn't get prometheus to validate the kublet cert for scraping, so
kublet → kubelet

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/prometheus-config.libsonnet
> +        // don't bother for now
End with period.

2021-03-17 19:55 UTC, beorn7 commented on prometheus-ksonnet/lib/prometheus-config.libsonnet
> +      // /metrics/cadvisor path
End with period. But perhaps we can also remove the whole comment as K8s 1.7 is ages ago.

2021-03-17 19:55 UTC, beorn7 commented on prometheus/scrape_configs.libsonnet
> +      // Drop any endpoint who's pod port name does not end with metrics
who's → whose.
End with period (the latter also for all the comments below).

2021-03-17 19:55 UTC, beorn7 commented on prometheus/scrape_configs.libsonnet
> +      },
Perhaps comment this stanza as well, as it is done for all the others.

2021-03-18 11:34 UTC, beorn7 approved these changes

2021-03-23 08:13 UTC, Duologic commented
rebased.

2021-03-23 09:38 UTC, merged