Shahzeb/asterisk mixin
grafana/jsonnet-libs pull request #749
Opened 2022-02-23 20:35 UTC by mshahzeb

Asterisk mixin for Asterisk integration https://github.com/grafana/cloud-onboarding/issues/1175

2022-02-23 20:38 UTC, mshahzeb commented
The mixin currently have JSON based dashboards.

It is planned to convert them to grafonnet based dashboards in next phase once integration is live.

2022-02-23 22:22 UTC, rgeyer requested changes
One small oversight, but otherwise it looks great!

2022-02-23 22:22 UTC, rgeyer commented on asterisk-mixin/README.md
> +dashboards based on the metrics exported by the [prometheus exporter in asterisk](https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+Configuration_res_prometheus). The mixin also creates a dashbo
Should Asterisk be always capitalized?

```suggestion
dashboards based on the metrics exported by the [prometheus exporter in Asterisk](https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+Configuration_res_prometheus). The mixin also creates a dashboard that
```

2022-02-23 22:22 UTC, rgeyer commented on asterisk-mixin/dashboards/asterisk-logs.json
> +        "uid": "grafanacloud-logs"
This repeats in this file, there are several panels which are hardcoded to use your loki datasource uid. You can just do a search and replace.

```suggestion
        "uid": "${loki_datasource}"
```

2022-02-23 23:21 UTC, mshahzeb commented on asterisk-mixin/README.md
> +dashboards based on the metrics exported by the [prometheus exporter in asterisk](https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+Configuration_res_prometheus). The mixin also creates a dashbo
Done - this is updated in latest commit

2022-02-24 00:40 UTC, rgeyer approved these changes
LGTM, thanks for the fixes. 🚀

2022-02-24 10:15 UTC, merged