Add Redis Enterprise Mixin
grafana/jsonnet-libs pull request #965
Opened 2023-04-06 17:44 UTC by schmikei

Adds 3 new dashboards and several new alerts for [Redis-Enterprise](https://docs.redis.com/latest/rs/clusters/monitoring/prometheus-metrics-definitions/). Hoping this provides users with a monitoring toolkit OOTB that helps them monitor and manage their Redis Enterprise Deployments.

Metric Definitions: https://docs.redis.com/latest/rs/clusters/monitoring/prometheus-metrics-definitions/

<details>
<summary> Screenshots </summary>
<img width="1739" alt="Screen Shot 2023-04-12 at 11 10 50 AM" src="https://user-images.githubusercontent.com/32067685/231532974-aa3f6f37-3487-4fe9-89cc-8091253147c3.png">
<img width="1718" alt="Screen Shot 2023-04-12 at 11 10 30 AM" src="https://user-images.githubusercontent.com/32067685/231532982-dcdc469e-7d79-428b-b1e0-64eb76524a9d.png">
<img width="1720" alt="Screen Shot 2023-04-12 at 10 57 11 AM" src="https://user-images.githubusercontent.com/32067685/231532990-14f3e8d8-fb91-45e7-8b0d-9d6a6c9ab8ef.png">
<img width="1722" alt="Screen Shot 2023-04-12 at 10 56 49 AM" src="https://user-images.githubusercontent.com/32067685/231532994-4f22eaa3-2d8e-4e94-8139-2910032d0673.png">
<img width="1723" alt="Screen Shot 2023-04-12 at 10 56 33 AM" src="https://user-images.githubusercontent.com/32067685/231533000-8372d16e-c3d4-461c-a16f-593bd715cffd.png">
</details>

2023-04-07 20:01 UTC, kuiperda commented on redis-enterprise-mixin/README.md
> +The Redis Enterprise overview dashboard provides details on the overall status of the Redis Enterprise cluster. Includes visualizations for important KPIs such as , nodes up, databases up, average re
'such as ,'

2023-04-07 21:02 UTC, kuiperda reviewed
Looks really good overall! Nice job!

2023-04-10 13:07 UTC, schmikei commented on redis-enterprise-mixin/dashboards/redis-enterprise-database.libsonnet
> +      },
Was designed for usability! I.e. less clutter on the panel!

2023-04-10 13:07 UTC, schmikei commented on redis-enterprise-mixin/README.md
> +![Screenshot of the Redis Enterprise keyspaces dashboard](https://storage.googleapis.com/grafanalabs-integration-assets/apache-cassandra/screenshots/keyspaces_1.png)
Yep! 👍

2023-04-10 13:07 UTC, schmikei commented on redis-enterprise-mixin/README.md
> +- ClusterOutOfMemory
Eh will keep it as is for now!

2023-04-14 16:19 UTC, schmikei commented
@rgeyer @v-zhuravlev @gloriasc @gaantunes 

When either of you have a free moment would you mind taking a peek at this?

2023-04-14 18:57 UTC, rgeyer commented on redis-enterprise-mixin/README.md
> +![Screenshot of the Redis Enterprise keyspaces dashboard](https://storage.googleapis.com/grafanalabs-integration-assets/apache-cassandra/screenshots/keyspaces_1.png)
Let's leave out the TODO screenshots for now. I'd track them with an issue on the repo, and you can follow up with another PR once the images are uploaded to our bucket. This saves possibly having them fall through the cracks when this PR gets merged.

2023-04-14 18:58 UTC, rgeyer approved these changes
Looks good to me! One comment RE: the images which are not yet uploaded, but otherwise I think this is good-to-go.

2023-04-17 09:52 UTC, v-zhuravlev commented
@schmikei hi, database/node average latency panels looks empty on screens. Is underlying metric available?

2023-04-17 10:00 UTC, v-zhuravlev requested changes
Great cluster overview dash! Please check small suggestions.

2023-04-17 16:26 UTC, schmikei commented
> @schmikei hi, database/node average latency panels looks empty on screens. Is underlying metric available?

Yep the metrics are available per documentation: https://docs.redis.com/6.2/rs/clusters/monitoring/prometheus-metrics-definitions/

Going to need to generate load for them though when we figure out active-active for our ref environment.

2023-04-17 16:31 UTC, schmikei commented on redis-enterprise-mixin/alerts/alerts.libsonnet
> -            alert: 'ClusterOutOfMemory',
Good catch!

2023-04-19 06:46 UTC, v-zhuravlev approved these changes
LGTM, thank you

2023-04-19 06:46 UTC, merged