Add OpenSearch mixin
grafana/jsonnet-libs pull request #973
Opened 2023-04-21 14:24 UTC by JonathanWamsley

Adds 2 dashboards and several new alerts for OpenSearch.

Dashboards:
- OpenSearch cluster overview
- OpenSearch node overview
- OpenSearch search and index overview

Alerts:
- OpenSearchYellowCluster
- OpenSearchRedCluster
- OpenSearchUnstableShardReallocation
- OpenSearchUnstableShardUnassigned
- OpenSearchModerateNodeDiskUsage
- OpenSearchHighNodeDiskUsage
- OpenSearchModerateNodeCPUUsage
- OpenSearchHighNodeCPUUsage
- OpenSearchModerateNodeMemoryUsage
- OpenSearchHighNodeMemoryUsage
- OpenSearchModerateRequestLatency
- OpenSearchModerateIndexLatency

2023-04-21 18:42 UTC, kuiperda commented on opensearch-mixin/.lint
> +    - dashboard: "OpenSearch search and index overview"
```suggestion
    - dashboard: "OpenSearch search and index overview"
  panel-units-rule:
    reason: "Custom units are used for better user experience in these panels"
    entries:
    - panel: (panel name)
```

run `make fmt` and then `make lint` which will give errors for panels that have custom units or no units. 
Should add each panel that this affects under `entries`

2023-04-21 19:19 UTC, kuiperda approved these changes
Looks good!

2023-04-21 20:52 UTC, StefanKurek requested changes

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/README.md
> +In order for the selectors to properly work for system logs ingested into your logs datasource, please also include the matching `instance`, `job`, and `cluster` labels onto the [scrape_configs](http
```suggestion
In order for the selectors to properly work for system logs ingested into your logs datasource, please also include the matching `job` and `opensearch_cluster` labels onto the [scrape_configs](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#scrape_configs) as to match the labels for ingested metrics.
```

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/README.md
> +          instance: '<your-instance-name>'
```suggestion
```

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/README.md
> +    alertsWarningShardUnassigned: 1,
```suggestion
    alertsWarningShardUnassigned: 0,
```

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              max by (job, cluster) (opensearch_cluster_status) == 1
```suggestion
              opensearch_cluster_status == 1
```

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              max by (job, cluster) (opensearch_cluster_status) == 2
```suggestion
              opensearch_cluster_status == 2
```

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              sum by(job, cluster) (opensearch_cluster_shards_number{type="relocating"}) > %(alertsWarningShardReallocations)s
```suggestion
              sum without(type) (opensearch_cluster_shards_number{type="relocating"}) > %(alertsWarningShardReallocations)s
```

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/config.libsonnet
> +    alertsWarningShardUnassigned: 1,
```suggestion
    alertsWarningShardUnassigned: 0,
```

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              sum by(job, cluster) (opensearch_cluster_shards_number{type="unassigned"}) > %(alertsWarningShardUnassigned)s
```suggestion
              sum without(type) (opensearch_cluster_shards_number{type="unassigned"}) > %(alertsWarningShardUnassigned)s
```

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              100 * sum by(node, job, cluster) ((opensearch_fs_path_total_bytes - opensearch_fs_path_free_bytes) / opensearch_fs_path_total_bytes) > %(alertsWarningDiskUsage)s
```suggestion
              100 * sum without(nodeid, path, mount, type) ((opensearch_fs_path_total_bytes - opensearch_fs_path_free_bytes) / opensearch_fs_path_total_bytes) > %(alertsWarningDiskUsage)s
```

2023-04-21 20:52 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              100 * sum by(node, job, cluster) ((opensearch_fs_path_total_bytes - opensearch_fs_path_free_bytes) / opensearch_fs_path_total_bytes) > %(alertsCriticalDiskUsage)s
```suggestion
              100 * sum without(nodeid, path, mount, type) ((opensearch_fs_path_total_bytes - opensearch_fs_path_free_bytes) / opensearch_fs_path_total_bytes) > %(alertsCriticalDiskUsage)s
```

2023-04-21 20:59 UTC, StefanKurek requested changes

2023-04-21 20:59 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              sum by(node, job, cluster) (opensearch_os_cpu_percent) > %(alertsWarningCPUUsage)s
```suggestion
              sum without(nodeid) (opensearch_os_cpu_percent) > %(alertsWarningCPUUsage)s
```

2023-04-21 20:59 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              sum by(node, job, cluster) (opensearch_os_cpu_percent) > %(alertsCriticalCPUUsage)s
```suggestion
              sum without(nodeid) (opensearch_os_cpu_percent) > %(alertsCriticalCPUUsage)s
```

2023-04-21 20:59 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              sum by(node, job, cluster) (opensearch_os_mem_used_percent) > %(alertsWarningMemoryUsage)s
```suggestion
              sum without(nodeid) (opensearch_os_mem_used_percent) > %(alertsWarningMemoryUsage)s
```

2023-04-21 20:59 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              sum by(node, job, cluster) (opensearch_os_mem_used_percent) > %(alertsCriticalMemoryUsage)s
```suggestion
              sum without(nodeid) (opensearch_os_mem_used_percent) > %(alertsCriticalMemoryUsage)s
```

2023-04-21 20:59 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              sum by(index, job, cluster) ((increase(opensearch_index_search_fetch_time_seconds{context="total"}[5m])+increase(opensearch_index_search_query_time_seconds{context="total"}[5m])+increas
```suggestion
              sum without(context) ((increase(opensearch_index_search_fetch_time_seconds{context="total"}[5m])+increase(opensearch_index_search_query_time_seconds{context="total"}[5m])+increase(opensearch_index_search_scroll_time_seconds{context="total"}[5m])) / clamp_min(increase(opensearch_index_search_fetch_count{context="total"}[5m])+increase(opensearch_index_search_query_count{context="total"}[5m])+increase(opensearch_index_search_scroll_count{context="total"}[5m]), 1)) > %(alertsWarningRequestLatency)s
```

2023-04-21 20:59 UTC, StefanKurek commented on opensearch-mixin/alerts/alerts.libsonnet
> +              sum by(job, cluster, index) (increase(opensearch_index_indexing_index_time_seconds[5m]) / clamp_min(increase(opensearch_index_indexing_index_count[5m]), 1)) > %(alertsWarningIndexLatenc
```suggestion
              sum without(context) (increase(opensearch_index_indexing_index_time_seconds{context="total"}[5m]) / clamp_min(increase(opensearch_index_indexing_index_count{context="total"}[5m]), 1)) > %(alertsWarningIndexLatency)s
```

2023-04-21 21:03 UTC, StefanKurek requested changes

2023-04-21 21:03 UTC, StefanKurek commented on opensearch-mixin/dashboards/opensearch-cluster-overview.libsonnet
> +      'topk(10, sum by(job, cluster, index) (increase(opensearch_index_indexing_index_time_seconds{job=~"$job", cluster=~"$opensearch_cluster"}[$__interval:]) / clamp_min(increase(opensearch_index_in
```suggestion
      'topk(10, sum by(job, cluster, index) (increase(opensearch_index_indexing_index_time_seconds{job=~"$job", cluster=~"$opensearch_cluster", context="total"}[$__interval:]) / clamp_min(increase(opensearch_index_indexing_index_count{job=~"$job", cluster=~"$opensearch_cluster", context="total"}[$__interval:]), 1)))',
```

2023-04-24 21:24 UTC, StefanKurek approved these changes

2023-04-26 13:23 UTC, Dasomeone reviewed
Couple minor things and what appears as missing legends/labels on the overview dashboard, but this is otherwise looking fantastic! 

Last little thing, I didn't run the linting but please make sure `mixtool lint mixin.libsonnet` returns no issues (you'll need to vender in grafonnet first)

2023-04-26 13:23 UTC, Dasomeone commented on opensearch-mixin/dashboards/opensearch-node-overview.libsonnet
Some broken row elements here in this dashboard:
![image](https://user-images.githubusercontent.com/1282515/234588003-2feaca91-eee7-4450-8e30-2cdd95c87f8c.png)
![image](https://user-images.githubusercontent.com/1282515/234588053-a60c4f03-7744-4f5c-923c-0740133b019a.png)

2023-04-26 13:23 UTC, Dasomeone commented on opensearch-mixin/dashboards/opensearch-search-and-index-overview.libsonnet
Another broken row element here
![image](https://user-images.githubusercontent.com/1282515/234588332-3fb8dd48-0ebd-46ba-96b0-7920cbab749a.png)

2023-04-26 14:10 UTC, JonathanWamsley commented on opensearch-mixin/dashboards/opensearch-cluster-overview.libsonnet
> +  title: 'Top nodes by CPU usage',
Hey Emily, I believe the panels are working correctly. For a single instance, it there are no legends shown. When I added the same query, then the legends appear just like in the sample app images shown above. Same applies for the Breakers tripped and Top nodes by disk usage panel, so I think this setup is good. ![Screenshot 2023-04-26 at 10 03 57 AM](https://user-images.githubusercontent.com/13648435/234600566-d669997f-c494-43c5-9176-53ffdf5aaad7.png)

I also updated the charts so now the row elements contain all the panels too.

2023-04-26 14:13 UTC, JonathanWamsley commented
> Last little thing, I didn't run the linting but please make sure `mixtool lint mixin.libsonnet` returns no issues (you'll need to vender in grafonnet first)

No linting issues here
![Screenshot 2023-04-26 at 10 12 33 AM](https://user-images.githubusercontent.com/13648435/234603038-35f6df63-d686-44d7-aebf-33b2df5596e8.png)

2023-04-27 13:36 UTC, Dasomeone commented on opensearch-mixin/dashboards/opensearch-cluster-overview.libsonnet
> +  title: 'Top nodes by CPU usage',
Ahh I see, that does explain it, thank you!

All looks good to me, thanks for all the hard work on this!

2023-04-27 13:36 UTC, Dasomeone approved these changes

2023-04-27 18:11 UTC, rgeyer approved these changes
LGTM, reviewers before me covered anything that stood out.

Thanks!

2023-04-27 18:11 UTC, rgeyer commented on opensearch-mixin/.lint
> +    reason: "Based on new convention we are using variable names prometheus_datasource and loki_datasource where as linter expects 'datasource'"
FYI, soon, these won't be necessary any more 🎉 

grafana/dashboard-linter#124

2023-04-28 17:03 UTC, merged